name: PSP Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Derle
        run: |
          mkdir -p build
          cd build
          psp-cmake ..
          make

      - name: EBOOT.PBP dosyasini yukle
        uses: actions/upload-artifact@v4
        with:
          name: MarioKartPSP
          path: build/EBOOT.PBP
